In [1]:
import pandas as pd
import requests
import time
import os
from tqdm import tqdm

In [2]:
df_krut = pd.read_csv('learner_corpus.csv', sep=';;;')
df_krut

/var/folders/v3/g9p917f512s52x0xb8r6htn00000gn/T/ipykernel_55518/4154161194.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_krut = pd.read_csv('learner_corpus.csv', sep=';;;')

,id,owner_id,created,title,body,author,filename,date1,date2,genre,...,level,time_limit,university,university_code,student_code,words,sentences,date_displayed,annotated,checked;;
0,1,NaN,2015-07-02 22:27:18,"абзац (Дизайн, 2 курс бак)",loaded from xml,курилова мария,/text_2014/DIZAJNERY2014/dolgi/KurilovaMarija_...,2013.0,2014.0,абзац,...,NaN,NaN,NaN,0.0,1.0,452,35,2013-2014,1,1
1,2,NaN,2015-07-02 22:27:18,"эссе (Дизайн, 2 курс бак)",loaded from xml,судакова мария,/text_2014/DIZAJNERY2014/dolgi/Domashneezadani...,2013.0,2014.0,эссе,...,NaN,NaN,NaN,0.0,2.0,518,42,2013-2014,1,1
2,3,NaN,2015-07-02 22:27:18,"абзац (Дизайн, 2 курс бак)",loaded from xml,мануйлова света,/text_2014/DIZAJNERY2014/dolgi/ManuylovaSvetaD...,2013.0,2014.0,абзац,...,NaN,NaN,NaN,0.0,3.0,491,31,2013-2014,1,1
3,4,NaN,2015-07-02 22:27:18,"абзац (Дизайн, 2 курс бак)",loaded from xml,черноброва наталья,/text_2014/DIZAJNERY2014/dolgi/chernobrova_5.prs,2013.0,2014.0,абзац,...,NaN,NaN,NaN,0.0,4.0,598,40,2013-2014,1,1
4,5,NaN,2015-07-02 22:27:18,"эссе (Дизайн, 2 курс бак)",loaded from xml,бардина анастасия,/text_2014/DIZAJNERY2014/dolgi/BardinaAnastasi...,2013.0,2014.0,эссе,...,NaN,NaN,NaN,0.0,5.0,291,23,2013-2014,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877,3956,NaN,2022-01-29 10:12:43,"семестровая работа (Журналистика, 2 курс бак)",В тексте чаще всего встречаются абстрактные су...,Новгородова,НовгородоваБЖУР201,2021.0,2021.0,семестровая работа,...,NaN,NaN,НИУ ВШЭ,NaN,NaN,320,15,2021,1,0
3878,3957,NaN,2022-01-29 10:21:51,"семестровая работа (Журналистика, 2 курс бак)",В тексте преобладают предметные и абстрактные ...,Пашечко,ПашечкоБЖУР201,2021.0,2021.0,семестровая работа,...,NaN,NaN,НИУ ВШЭ,NaN,NaN,334,21,2021,1,0
3879,3958,NaN,2022-01-29 10:35:46,"семестровая работа (Журналистика, 2 курс бак)",Контрольная работа. Текст “Медузы”Больше всего...,Ушмодина,УшмодинаБЖУР201,2021.0,2021.0,семестровая работа,...,NaN,NaN,НИУ ВШЭ,NaN,NaN,337,19,2021,1,0
3880,3959,NaN,2022-01-29 10:38:39,"семестровая работа (Журналистика, 2 курс бак)",Текст 2: «Медуза» – еще один удар по журналист...,Шевчук,ШевчукБЖУР201,2021.0,2021.0,семестровая работа,...,NaN,NaN,НИУ ВШЭ,NaN,NaN,435,28,2021,1,0
3881,3960,NaN,2022-01-29 10:49:28,"семестровая работа (Журналистика, 2 курс бак)",В выбранном фрагменте чаще можно было встретит...,Логвин,ЛогвинБЖУР201,2021.0,2021.0,семестровая работа,...,NaN,NaN,НИУ ВШЭ,NaN,NaN,288,17,2021,1,0

In [16]:
output_dir = 'ru_standard'
os.makedirs(output_dir, exist_ok=True)
for index, text in tqdm(df_krut['body'].items()):
    if text.strip and text.strip() != 'loaded from xml':
        with open(f'{output_dir}/text_{index}.txt', 'w') as f:
            f.write(text)

3882it [00:00, 33187.98it/s]

In [ ]:
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "*/*",
    "Connection": "keep-alive",
}

def download_file(i, save_dir):
    url = f"http://www.web-corpora.net/RLC/download_file/{i}/text"
    
    try:
        r = requests.get(url, headers=headers, timeout=10)
        
        if r.status_code == 200 and r.content:
            filepath = os.path.join(save_dir, f"text_{i}.txt")
            with open(filepath, "wb") as f:
                f.write(r.content)
            # print(f"OK {i}")
        else:
            print(f"FAIL {i} status={r.status_code}")
    
    except Exception as e:
        print(f"ERROR {i}: {e}")


save_dir = "ru_non_standard"
os.makedirs(save_dir, exist_ok=True)

for i in tqdm(range(3000, 3283)):
    download_file(i, save_dir)
    time.sleep(1)

In [6]:
df_pwa = pd.read_csv('papers_with_abctracts.csv', sep=',')
df_pwa

,имя файла,название,аннотация,текст статьи
0,Adrova_IMS_2013.txt,"Исследование алгоритмов хеширования, используе...",Настоящая статья посвящена исследованию алгори...,https://raw.githubusercontent.com/CompLinguist...
1,Aksarin_IMS_2013.txt,От театра в интернет к интернет-театру,Интернет оказывает существенное влияниена стил...,https://raw.githubusercontent.com/CompLinguist...
2,Arzumanyan_IMS_2013.txt,Визуализация и восприятие информации в гуманит...,Рост количества информации и скорости информац...,https://raw.githubusercontent.com/CompLinguist...
3,Bershadskaya_IMS_2013.txt,Востребованность услуг электронного правительс...,В статье представлены результаты мониторинга о...,https://raw.githubusercontent.com/CompLinguist...
4,Bikkulov_IMS_2013.txt,Подростковые самоубийства в обсуждениях блогос...,В статье рассмотрена проблематика подростковых...,https://raw.githubusercontent.com/CompLinguist...
...,...,...,...,...
322,Volf_CL_2021.txt,АВТОМАТИЧЕСКАЯ РАЗМЕТКА ЗАИМСТВОВАНИЙИЗ РУССКО...,Статья посвящена вопросам автоматической аннот...,https://raw.githubusercontent.com/CompLinguist...
323,Zakharova_CL_2021.txt,ВОЗМОЖНОСТЬ КОРПУСА: ОТПРАВНЫЕ ТОЧКИ И ОПЫТСОЗ...,"В статье описывается один из современных, акти...",https://raw.githubusercontent.com/CompLinguist...
324,Zemicheva_CL_2021.txt,"ДРУГ, ПОДРУГА, ТОВАРИЩ, ЗНАКОМЫЙ :СПЕЦИФИКА СЕ...",Цель статьи — выявить своеобразие использовани...,https://raw.githubusercontent.com/CompLinguist...
325,Zhang_CL_2021.txt,КОРПУСНЫЙ АНАЛИЗ ЛЕКСИЧЕСКОГО НАПОЛНЕНИЯ КОНЦЕ...,Концепт «государство» является важной составля...,https://raw.githubusercontent.com/CompLinguist...
326,Zubov_CL_2021.txt,ВМЕСТЕ ИЛИ ВРОЗЬ: НЕОДНОСЛОВНЫЕ ЕДИНИЦЫ В КОРП...,"В статье описывается первый этап исследования,...",https://raw.githubusercontent.com/CompLinguist...

In [8]:
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "*/*",
    "Connection": "keep-alive",
}

output_dir = 'ru_standard/articles_kaggle'
os.makedirs(output_dir, exist_ok=True)

for index, row in tqdm(df_pwa.iterrows()):
    url = row['текст статьи']
    filename = row['имя файла']
    filepath = os.path.join(output_dir, filename)
    
    try:
        r = requests.get(url, headers=headers, timeout=10)
        
        if r.status_code == 200:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(r.text)
            # print(f"OK {filename}")
        else:
            print(f"FAIL {filename} status={r.status_code}")
    
    except Exception as e:
        print(f"ERROR {filename}: {e}")

    time.sleep(1)  # To be respectful to the server

200it [05:10,  1.56s/it]

FAIL Tatur_IMS_2023.txt status=404

327it [08:26,  1.55s/it]